#!/bin/bash
echo "For which domain would you like to grab the sitemaps of?"
read domain

mkdir $domain
cd $domain
wget http://$domain/sitemap.xml
grep http sitemap.xml  | grep http | grep xml | sed 's/<loc>//' | sed 's/<\/loc>//' |  awk '{print $1}' | grep "^http" > maps
wget -i maps

grep http *sitemap*  | awk '{print $2}' |  grep -v xml | sed 's/<loc>//' | sed 's/<\/loc>//' |  grep "^http" | sort  | uniq > allurls.txt

VAL=`wc -l allurls.txt | awk '{print $1}'`

read -p "Would you like to see the $VAL urls? (y/n)" choice

case "$choice" in
  y|Y ) cat allurls.txt;;
  n|N ) echo "They have been added to $domain/allurls.txt";;
  * ) echo "invalid";;
esac

